services:
  test-ruby3.2:
    build:
      context: .
      args:
        RUBY_VERSION: "3.2"
  test-ruby3.4:
    build:
      context: .
      args:
        RUBY_VERSION: "3.4"
  shell:
    build:
      context: .
      args:
        RUBY_VERSION: "3.4"
    volumes:
      - .:/app
    command: bash
