services:
  test-ruby2:
    build:
      context: .
      args:
        RUBY_VERSION: "2.7"
  test-ruby3:
    build:
      context: .
      args:
        RUBY_VERSION: "3.3"
  shell:
    build:
      context: .
      args:
        RUBY_VERSION: "3.3"
    volumes:
      - .:/app
    command: bash
